### ISSUE TITLE
Reset State

### ISSUE THREAD

**Issue by JuGault** [amzhang/ngrx-loading-state#2]
Hi, is there a solution to reset the state of an action after its success? automatically ? with a timer?

**Comment by amzhang** [comment]
Could you describe the use case?

**Comment by JuGault** [comment]
Well, please find my use case in the following example :

I have an alert displayed using "ngx-toaster" on the state.success of an action "Save" dispatched on a click of a button,

this works perfectly fine on the button click, but the problem is when I navigate out of my component and then back on the component, the loading state is still preserved and I have the toaster alert displayed.

**Comment by amzhang** [comment]
I see. The loading states are meant to be persistent so that other components can rely on it. What you are looking for is an event: when the state transitions from `loading` to `success`.

There are a couple of ways to do that that I can think of:

1. Listen to the "success" action in the component. Don't forget to unsub when the component unloads. May I suggest the excellent `subsink` lib

2. Use the ID based loading state: use the current time or just a random number as the ID, such that each "load" action will have its own unique state. You then select the state using the ID you just created. This does lead to a growing list of loading states every time "Save" is clicked. I don't have a way to clear them yet, but the loading states are very small, so I don't expect the buildup to be an issue. There is a demo for ID loading states here: https://stackblitz.com/edit/angular-ivy-rocjzb?file=src%2Fapp%2Fapp.component.ts

**Comment by amzhang** [comment]
This approach might be best:
3. Subscribe to the state selector. Use NxJs [pairwise](https://www.learnrxjs.io/learn-rxjs/operators/combination/pairwise) operator to detect the state changes from `loading` to `success`. Then open your snackbar message and set a timeout on it.

**Comment by JuGault** [comment]
Thanks for his answers. We had already implemented some of them, something like the ShoulIssueFetch method which is based on the successTimestamp with a timer, but this is not satisfactory as it stands. Would it be possible for you to create a method that allows you to reset a particular state or all states?

**Comment by amzhang** [comment]
If you want to clear the loading state you could create an Ngrx action that removes the key corresponding to a loading states in the `loadingStates` variable in the ngrx state. Just delete the key.

**Comment by JuGault** [comment]
Hello how do you do? do you have an example because the state being in readonly , we have very little possibility of action on the latter to my knowledge.
thank you

**Comment by amzhang** [comment]
https://stackblitz.com/edit/angular-ivy-gtua4h?file=src%2Fapp%2Fdata-access%2Fsimple.reducer.ts

The change are in `simple.reducer.ts`

**Comment by amzhang** [comment]
Assuming above solved the issue.
